import {
  CktModelEnum,
  ControlModeOptionEnum,
  EarthModelEnum,
  LoadModelEnum,
  LoadShapeClassEnum,
  ModeEnum,
  RandomEnum,
  ReduceOptionEnum,
} from "@enums/enums";

export default interface OpenDSSOptionsInterface {
  /** Set default annual growth rate, percent, for loads with no growth curve specified. Default is 2.5. */
  "%growth"?: number;
  /** Percent mean to use for global load multiplier. Default is 65%. */
  "%mean"?: number;
  /** Sets the Normal rating of all lines to a specified percent of the emergency rating.  Note: This action takes place immediately. Only the in-memory value is changed for the duration of the run. */
  "%normal"?: number;
  /** Percent Standard deviation to use for global load multiplier. Default is 9%. */
  "%stddev"?: number;
  /** Gets/Sets the number of the active actor, if the value is * (set active actor=*), the commands send after this instruction will be aplied to all the actors. */
  activeActor?: number;
  /** Gets progress (%) for all the actors when performing a task */
  actorProgress?: number;
  /** {Generator | Capacitor} Default is Generator. Type of device for AutoAdd Mode. */
  addtype?: number;
  /** {Normal | Newton}  Solution algorithm type.  Normal is a fixed point iteration that is a little quicker than the Newton iteration.  Normal is adequate for most radial distribution circuits.  Newton is more robust for circuits that are difficult to solve.Diakoptics is used for accelerating the simulation using multicore computers */
  algorithm?: number;
  /** Sets the connected kVA allocation factors for all loads in the active circuit to the value given. */
  allocationfactors?: number;
  /** {YES/TRUE | NO/FALSE}   Default is No. Flag to indicate if it is OK to have devices of same name in the same class. If No, then a New command is treated as an Edit command. If Yes, then a New command will always result in a device being added. */
  allowduplicates?: boolean;
  /** Array of bus names to include in AutoAdd searches. Or, you can specify a text file holding the names, one to a line, by using the syntax (file=filename) instead of the actual array elements. Default is null, which results in the program using either the buses in the EnergyMeter object zones or, if no EnergyMeters, all the buses, which can make for lengthy solution times.  */
  autobuslist?: string[]; // FIXME:
  /** Default = 60. Set the fundamental frequency for harmonic solution and the default base frequency for all impedance quantities. Side effect: also changes the value of the solution frequency. Saved as default for next circuit. */
  basefrequency?: number;
  /** Set Active Bus by name.  Can also be done with Select and SetkVBase commands and the "Set Terminal="  option. The bus connected to the active terminal becomes the active bus. See Zsc and Zsc012 commands. */
  bus?: number;
  /** Size of capacitor, kVAR, to automatically add to system.  Default is 600.0. */
  capkVAR?: number;
  /** Numeric marker code (0..47 -- see Users Manual) for Capacitors. Default is 38. */
  capMarkerCode?: number;
  /** Size of Capacitor marker. Default is 3. */
  capMarkerSize?: number;
  /** Name of case for yearly simulations with demand interval data. Becomes the name of the subdirectory under which all the year data are stored. Default = circuit name  */
  casename?: string;
  /** Sets the CFactors for for all loads in the active circuit to the value given. */
  cfactors?: number;
  /** Set the active circuit by name. */
  circuit?: string;
  /** {Multiphase | Positive}  Default = Multiphase.  Designates whether circuit model is to interpreted as a normal multi-phase model or a positive-sequence only model */
  cktmodel?: CktModelEnum;
  /** Synonym for Type=. (See above) */
  class?: number;
  /** Activates/Deactivates the option for concatenate the reports generated by the existing actors, if Yes, everytime the usera show/export monitor command the report will include the data generated by all the actors, otherwise the report will containThe data generated by the active actor */
  concatenateReports?: boolean;
  /** {OFF | STATIC |EVENT | TIME}  Default is "STATIC".  Control mode for the solution. Set to OFF to prevent controls from changing. */
  controlMode?: ControlModeOptionEnum;
  /** (default -1)Gets/Sets the CPU to be used by the active actor. If negative (-1) means that the actor affinity is to all the CPUs and will be executed in the */
  CPU?: number;
  /** Default is 1.0. Relative size (a multiplier applied to default size) of daisy circles on daisy plot. */
  daisysize?: number;
  /** Set the data path for files written or read by the DSS. */
  datapath?: string;
  /** Set Default Base Frequency, Hz. Side effect: Sets solution Frequency and default Circuit Base Frequency. This value is saved when the DSS closes down. */
  defaultBaseFrequency?: number;
  /** Default daily load shape name. Default value is "default", which is a 24-hour curve defined when the DSS is started. */
  defaultdaily?: string;
  /** Default yearly load shape name. Default value is "default", which is a 24-hour curve defined when the DSS is started. */
  defaultyearly?: string;
  /** {YES/TRUE | NO/FALSE} Default = no. Set for keeping demand interval data for daily, yearly, etc, simulations. Side Effect:  Resets all meters!!! */
  demandInterval?: boolean;
  /** {YES/TRUE | NO/FALSE} Default = FALSE.  Set to Yes/True if you wish a separate demand interval (DI) file written for each meter.  Otherwise, only the totalizing meters are written. */
  dIVerbose?: boolean;
  /** Executive.DSSVisualizationTool */
  dSSVisualizationTool?: number;
  /** One of {Carson | FullCarson | Deri*}.  Default is Deri, which is a  fit to the Full Carson that works well into high frequencies. "Carson" is the simplified Carson method that is typically used for 50/60 Hz power flow programs. Applies only to Line objects that use LineGeometry objects to compute impedances. */
  earthModel?: EarthModelEnum;
  /** Set the command string required to start up the editor preferred by the user. Does not require a circuit defined. */
  editor?: string;
  /** Sets the active DSS element by name. You can use the complete object spec (class.name) or just the name.  if full name is specifed, class becomes the active class, also. */
  element?: string;
  /** Maximum permissible per unit voltage for emergency (contingency) conditions. Default is 1.08. */
  emergvmaxpu?: number;
  /** Minimum permissible per unit voltage for emergency (contingency) conditions. Default is 0.90. */
  emergvminpu?: number;
  /** {YES/TRUE | NO/FALSE*} Sets/gets the default for the eventlog. After changing this flags the model needs to be recompiled to take effect. */
  eventLogDefault?: boolean;
  /** Sets the frequency for the solution of the active circuit. */
  frequency?: number;
  /** Numeric marker code (0..47 see Users Manual) for Fuse elements. Default is 25. */
  fuseMarkerCode?: number;
  /** Size of Fuse marker. Default is 1. */
  fuseMarkerSize?: number;
  /** Size of generator, kW, to automatically add to system. Default is 1000.0 */
  genkw?: number;
  /** Global multiplier for the kW output of every generator in the circuit. Default is 1.0. Applies to all but Autoadd solution modes. Ignored for generators designated as Status=Fixed. */
  genmult?: number;
  /** Power factor of generator to assume for automatic addition. Default is 1.0. */
  genpf?: number;
  /** Alternate name for time step size. */
  h?: string;
  /** {ALL | (list of harmonics) }  Default = ALL. Array of harmonics for which to perform a solution in Harmonics mode. If ALL, then solution is performed for all harmonics defined in spectra currently being used. Otherwise, specify a more limited list such as:  */
  harmonics?: "ALL" | string[];
  /** Sets the hour used for the start time of the solution. */
  hour?: number;
  /** Array of bus names to keep when performing circuit reductions. You can specify a text file holding the names, one to a line, by using the syntax (file=filename) instead of the actual array elements. Command is cumulative (reset keeplist first). Reduction algorithm may keep other buses automatically.  */
  keepList?: string[];
  /** Keeploads = Y/N option for ReduceOption Laterals option */
  keepLoad?: boolean;
  /** Set Load-Duration Curve. Global load multiplier is defined by this curve for LD1 and LD2 solution modes. Default is Nil. */
  lDCurve?: number;
  /** Executive.LineTypes */
  lineTypes?: number;
  /** {Powerflow | Admittance} depending on the type of solution you wish to perform. If admittance, a non-iterative, direct solution is done with all loads and generators modeled by their equivalent admittance. */
  loadModel?: LoadModelEnum;
  /** Global load multiplier for this circuit.  Does not affect loads designated to be "fixed".  All other base kW values are multiplied by this number. Defaults to 1.0 when the circuit is created. As with other values, it always stays at the last value to which it was set until changed again. */
  loadMult?: number;
  /** ={Daily | Yearly | Duty | None*} Default loadshape class to use for mode=time and mode=dynamic simulations. Loads and generators, etc., will follow this shape as time is advanced. Default value is None. That is, Load will not vary with time. */
  loadShapeClass?: LoadShapeClassEnum;
  /** {YES/TRUE | NO/FALSE} Default = FALSE.  Significant solution events are added to the Event Log, primarily for debugging. */
  log?: boolean;
  /** Executive.LongLineCorrection */
  longLineCorrection?: number;
  /** Which EnergyMeter register(s) to use for Losses in AutoAdd Mode. May be one or more registers.  if more than one, register values are summed together. Array of integer values > 0.  Defaults to 13 (for Zone kWh Losses).  */
  lossregs?: number;
  /** Weighting factor for Losses in AutoAdd functions.  Defaults to 1.0. */
  lossweight?: number;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark Capacitor locations with a symbol. See CapMarkerCode. */
  markCapacitors?: boolean;
  /** Number code for node marker on circuit plots. Number from 0 to 47. Default is 16 (open circle). 24 is solid circle. Try other values for other symbols. See also Nodewidth */
  markercode?: number;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark Fuse locations with a symbol. See FuseMarkerCode and FuseMarkerSize. */
  markFuses?: boolean;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark PVSystem locations with a symbol. See PVMarkerCode and PVMarkerSize. */
  markPVSystems?: boolean;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark Recloser locations with a symbol. See RecloserMarkerCode and RecloserMarkerSize. */
  markReclosers?: boolean;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark Regulator locations with a symbol. See RegMarkerCode. */
  markRegulators?: boolean;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark Relay locations with a symbol. See RelayMarkerCode and RelayMarkerSize. */
  markRelays?: boolean;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark Storage locations with a symbol. See StoreMarkerCode and StoreMarkerSize. */
  markStorage?: boolean;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark lines that are switches or are isolated with a symbol. See SwitchMarkerCode. */
  markswitches?: boolean;
  /** {YES/TRUE | NO/FALSE}  Default is NO. Mark transformer locations with a symbol. See TransMarkerCode. The coordinate of one of the buses for winding 1 or 2 must be defined for the symbol to show */
  marktransformers?: boolean;
  /** Max control iterations per solution.  Default is 10. */
  maxcontroliter?: number;
  /** Sets the maximum allowable iterations for power flow solutions. Default is 15. */
  maxiterations?: number;
  /** Minimum number of iterations required for a solution. Default is 2. */
  minIterations?: number;
  /** Set the solution Mode: One of Snapshot,
   * Daily,
   * Yearly (follow Yearly curve),
   * DIrect,
   * DUtycycle,
   * Time, ( see LoadShapeClass option)
   * DYnamic, ( see LoadShapeClass option)
   * Harmonic,
   * HarmonicT, (sequential Harmonic Mode)
   * M1 (Monte Carlo 1),
   * M2 (Monte Carlo 2),
   * M3 (Monte Carlo 3),
   * Faultstudy,
   * MF (monte carlo fault study)
   * Peakday,
   * LD1 (load-duration 1)
   * LD2 (load-duration 2)
   * AutoAdd (see AddType)
   * YearlyVQ (Yearly Vector Quantiaztion)
   * DutyVQ (Duty Vector Quantiaztion)
   */
  mode?: ModeEnum;
  /** {YES/TRUE | NO/FALSE}  Default is NO. For Harmonic solution, neglect the Load shunt admittance branch that can siphon off some of the Load injection current.  */
  neglectLoadY?: boolean;
  /** Width of node marker. Default=1. See MarkerCode */
  nodewidth?: number;
  /** Maximum permissible per unit voltage for normal conditions. Default is 1.05. */
  normvmaxpu?: number;
  /** Minimum permissible per unit voltage for normal conditions. Default is 0.95. */
  normvminpu?: number;
  /** Delivers the number of Actors created by the user, 1 is the default */
  numActors?: number;
  /** Default is 2. Maximum number of iterations for load allocations for each time the AllocateLoads or Estimate command is given. */
  numallociterations?: number;
  /** Delivers the number of Non-uniform memory access nodes (NUMA Nodes) available on the machine (read Only). This information is vital when workingwith processor clusters (HPC). It will help you know the number of processors in the cluster */
  NUMANodes?: number;
  /** Number of solutions or time steps to perform for each Solve command. Defaults for selected modes:
   * Daily = 24
   * Yearly = 8760
   * Duty = 100
   */
  number?: number;
  /** Delivers the number of physical processors (Cores) available on the computer. If your computers processor has less than 64 cores, this number should be equal to the half of the available CPUs, otherise the number should  be the same (Read Only) */
  numCores?: number;
  /** Delivers the number of threads (CPUs) available on the machine (read Only) */
  numCPUs?: number;
  /** Synonym for Element=. (See above) */
  object?: number;
  /** {YES/TRUE | NO/FALSE} Default = FALSE. For yearly solution mode, sets overload reporting on/off. DemandInterval must be set to true for this to have effect. */
  overloadreport?: boolean;
  /** Activates/Deactivates the parallel machine in OpenDSS, if deactivated OpenDSS will behave sequentially */
  parallel?: boolean;
  /** Sets the PRICESHAPE object to use to obtain for price signal. Default is none (null string). If none, price signal either remains constant or is set by an external process using Set Price= option. Curve is defined as a PRICESHAPE  in actual values (not normalized) and should be defined to correspond to the type of analysis being performed (daily, yearly, etc.). */
  pricecurve?: string;
  /** Sets the present price signal ($/MWh) for the circuit.  Default value is 25. */
  pricesignal?: number;
  /** The time in microseconds to execute the solve process in the most recent time step or solution (read only) */
  processTime?: number;
  /** Numeric marker code (0..47 see Users Manual) for PVSystems and PVSystem. Default is 15. */
  pVMarkerCode?: number;
  /** Size of PVsystem and PVSystem markers. Default is 1. */
  pVMarkerSize?: number;
  /** {YES/TRUE | NO/FALSE} Default = FALSE. When set to TRUE/YES, clears the query log file and thereafter appends the time-stamped Result string contents to the log file after a query command, ?. */
  queryLog?: boolean;
  /** One of [Uniform | Gaussian | Lognormal | None ] for Monte Carlo Variables. */
  random?: RandomEnum;
  /** Numeric marker code (0..47 see Users Manual) for Recloser elements. Default is 17. (color=Lime) */
  recloserMarkerCode?: number;
  /** Size of Recloser marker. Default is 5. */
  recloserMarkerSize?: number;
  /** {YES/TRUE | NO/FALSE} Default = FALSE. Opens DSSRecorder.DSS in DSS install folder and enables recording of all commands that come through the text command interface. Closed by either setting to NO/FALSE or exiting the program. When closed by this command, the file name can be found in the Result. Does not require a circuit defined. */
  recorder?: boolean;
  /** { Default or [null] | Shortlines [Zmag=nnn] | MergeParallel | BreakLoops | Switches | Ends | Laterals}  Strategy for reducing feeders. Default is to eliminate all dangling end buses and buses without load, caps, or taps.
   *
   * "Shortlines [Zmag=0.02]" merges short branches with impedance less than Zmag (default = 0.02 ohms)
   *
   * "MergeParallel" merges lines that have been found to be in parallel
   *
   * "Breakloops" disables one of the lines at the head of a loop.
   *
   * "Ends" eliminates dangling ends only.
   *
   * "Switches" merges switches with downline lines and eliminates dangling switches.
   *
   * "Laterals [Keepload=Yes/No]" uses the Remove command to eliminate 1-phase laterals and optionally lump the load back to the 2- or 3-phase feeder (default behavior).
   *
   * Marking buses with "Keeplist" will prevent their elimination.
   */
  reduceOption?: ReduceOptionEnum;
  /** {YES/TRUE | NO/FALSE}  Default is Yes. Update Windows Registry values upon exiting.  You might want to turn this off if you temporarily change fonts or DefaultBaseFrequency, for example. */
  registryUpdate?: boolean;
  /** Numeric marker code (0..47 see Users Manual) for Regulators. Default is 17. (red) */
  regMarkerCode?: number;
  /** Size of Regulator marker. Default is 5. */
  regMarkerSize?: number;
  /** Numeric marker code (0..47 see Users Manual) for Relay elements. Default is 17. (Color=Lime) */
  relayMarkerCode?: number;
  /** Size of Relay marker. Default is 5. */
  relayMarkerSize?: number;
  /** {YES/TRUE | NO/FALSE} Overrides default value for sampling EnergyMeter objects at the end of the solution loop. Normally Time and Duty modes do not automatically sample EnergyMeters whereas Daily, Yearly, M1, M2, M3, LD1 and LD2 modes do. Use this Option to turn sampling on or off */
  sampleEnergyMeters?: boolean;
  /** {YES/TRUE | NO/FALSE} Default = FALSE. Enables/disables the seasonal selection of the rating for determining if an element is overloaded. When enabled, the energy meter willlook for the rating (NormAmps) using the SeasonSignal  to evaluate if the PDElement is overloaded */
  seasonRating?: boolean;
  /** It is the name of the XY curve defining the ratings seasonal change for the PDElements in the model when performing QSTS simulations. The seasonal ratings need to be definedat the PDElement or at the general object definition such as linecodes, lineGeometry, etc. */
  seasonSignal?: string;
  /** Sets the seconds from the hour for the start time of the solution. */
  sec?: number;
  /** Executive.ShowExport */
  showExport?: number;
  /** Executive.ShowReports */
  showReports?: number;
  /** Sets the time step size for the active circuit.  Default units are s. May also be specified in minutes or hours by appending "m" or "h" to the value. For example: */
  stepsize?: number;
  /** Process time + meter sampling time in microseconds for most recent time step - (read only) */
  stepTime?: number;
  /** Numeric marker code (0..47 see Users Manual) for Storage elements. Default is 9. */
  storeMarkerCode?: number;
  /** Size of Storage marker. Default is 1. */
  storeMarkerSize?: number;
  /** Numeric marker code for lines with switches or are isolated from the circuit. Default is 4. See markswitches option. */
  switchmarkercode?: number;
  /** Set the active terminal of the active circuit element. May also be done with Select command. */
  terminal?: string;
  /** Specify the solution start time as an array: */
  time?: number[];
  /** Sets the solution tolerance.  Default is 0.0001. */
  tolerance?: number;
  /** The accumulated time in microseconds to solve the circuit since the last reset. Set this value to reset the accumulator. */
  totalTime?: number;
  /** {YES/TRUE | NO/FALSE}  Set to YES to trace the actions taken in the control queue.  Creates a file named TRACE_CONTROLQUEUE.CSV in the default directory. The names of all circuit elements taking an action are logged. */
  tracecontrol?: boolean;
  /** Numeric marker code (0..47 see Users Manual) for transformers. Default is 35. See markstransformers option. */
  transMarkerCode?: number;
  /** Size of transformer marker. Default is 1. */
  transMarkerSize?: number;
  /** {YES/TRUE | NO/FALSE}  Default is "No/False". Specifies whether to use trapezoidal integration for accumulating energy meter registers. Applies to EnergyMeter and Generator objects.  Default method simply multiplies the present value of the registers times the width of the interval (Euler). Trapezoidal is more accurate when there are sharp changes in a load shape or unequal intervals. Trapezoidal is automatically used for some load-duration curve simulations where the interval size varies considerably. Keep in mind that for Trapezoidal, you have to solve one more point than the number of intervals. That is, to do a Daily simulation on a 24-hr load shape, you would set Number=25 to force a solution at the first point again to establish the last (24th) interval. */
  trapezoidal?: boolean;
  /** Sets the active DSS class type.  Same as Class=... */
  type?: number;
  /** Which EnergyMeter register(s) to use for UE in AutoAdd Mode. May be one or more registers.  if more than one, register values are summed together. Array of integer values > 0.  Defaults to 11 (for Load EEN).  */
  uEregs?: number; // FIXME:
  /** Weighting factor for UE/EEN in AutoAdd functions.  Defaults to 1.0. */
  UEweight?: number;
  /** Define legal bus voltage bases for this circuit.  Enter an array of the legal voltage bases, in phase-to-phase voltages, for example: */
  voltagebases?: number[];
  /** {YES/TRUE | NO/FALSE} Default = FALSE. For yearly solution mode, sets voltage exception reporting on/off. DemandInterval must be set to true for this to have effect. */
  voltexceptionreport?: boolean;
  /** Sets the Year (integer number) to be used for the solution. for certain solution types, this determines the growth multiplier. */
  year?: number;
  /** Sets the Zmag option (in Ohms) for ReduceOption Shortlines option. Lines have less line mode impedance are reduced. */
  zmag?: number;
  /** {YES/TRUE | NO/FALSE}  Default is No. if No, then meter zones are recomputed each time there is a change in the circuit. If Yes, then meter zones are not recomputed unless they have not yet been computed. Meter zones are normally recomputed on Solve command following a circuit change. */
  zonelock?: boolean;
}
