name: CI

on:
    push:
        branches: ["master"]
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        name: Build and Test
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Enable Corepack before setting up Node
              run: corepack enable
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn

            - name: Update yarn
              run: yarn set version 4.1.0

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn run build

            - name: Typecheck
              run: yarn run typecheck

            - name: Lint
              run: yarn run lint

            - name: Test
              run: yarn run test
