name: Version

on:
    push:
        branches: ["master"]

jobs:
    release:
        name: Publish
        timeout-minutes: 15
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: pnpm release

            # - name: Create Release Pull Request
            #   id: changesets
            #   uses: changesets/action@v1
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build
              run: pnpm run build

            # - name: Package
            #   if: steps.changesets.outputs.hasChangesets == 'true'
            #   run: pnpm run package

            # - name: Release
            #   if: steps.changesets.outputs.hasChangesets == 'true'
            #   run: pnpm run release

            # - name: Package
            #   if: steps.changesets.outputs.hasChangesets == 'true'
            #   run: git push --follow-tags

            # - name: Upload
            #   if: steps.changesets.outputs.hasChangesets == 'true'
            #   uses: softprops/action-gh-release@v2
            #   with:
            #       files: apps/desktop/releases/*.exe
